CREATE TABLE import.general
(
	id serial not null,
	audityear varchar(4),
	dbkey varchar(10),
	typeofentity varchar(50),
	fyenddate varchar(20),
	audittype varchar(1),
	periodcovered varchar(1),
	numbermonths varchar(3),
	ein varchar(9),
	multipleeins varchar(1),
	einsubcode varchar(9),
	duns varchar(9),
	multipleduns varchar(1),
	auditeename varchar(70),
	street1 varchar(45),
	street2 varchar(45),
	city varchar(30),
	state varchar(2),
	zipcode varchar(9),
	auditeecontact varchar(50),
	auditeetitle varchar(40),
	auditeephone varchar(10),
	auditeefax varchar(10),
	auditeeemail varchar(60),
	auditeedatesigned varchar(10),
	auditeenametitle varchar(70),
	cpafirmname varchar(64),
	cpastreet1 varchar(45),
	cpastreet2 varchar(45),
	cpacity varchar(30),
	cpastate varchar(2),
	cpazipcode varchar(9),
	cpacontact varchar(50),
	cpatitle varchar(40),
	cpaphone varchar(10),
	cpafax varchar(10),
	cpaemail varchar(60),
	cpadatesigned varchar(10),
	cog_over varchar(10),
	cogagency varchar(10),
	oversightagency varchar(10),
	typereport_fs varchar(3),
	sp_framework varchar(15),
	sp_framework_required varchar(1),
	typereport_sp_framework varchar(15),
	goingconcern varchar(1),
	reportablecondition varchar(1),
	materialweakness varchar(1),
	materialnoncompliance varchar(1),
	typereport_mp varchar(3),
	dup_reports varchar(1),
	dollarthreshold varchar(12),
	lowrisk varchar(1),
	reportablecondition_mp varchar(1),
	materialweakness_mp varchar(4),
	qcosts varchar(1),
	cyfindings varchar(1),
	pyschedule varchar(1),
	totfedexpend varchar(12),
	datefirewall varchar(20),
	previousdatefirewall varchar(20),
	reportrequired varchar(1),
	multiple_cpas varchar(1),
	auditor_ein varchar(9),
	facaccepteddate varchar(10),
	CONSTRAINT pk_import_general PRIMARY KEY ("id")

);

